; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35229.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_Avx2WmemEnabledWeakValue
;	COMDAT _Avx2WmemEnabledWeakValue
_BSS	SEGMENT
_Avx2WmemEnabledWeakValue DD 01H DUP (?)
_BSS	ENDS
CONST	SEGMENT
$SG57742 DB	'Stack is empty', 00H
	ORG $+1
$SG57749 DB	'Stack is empty', 00H
	ORG $+1
$SG57795 DB	'Stack is empty', 00H
	ORG $+1
$SG57802 DB	'Stack is empty', 00H
	ORG $+1
$SG57838 DB	'Stack is empty', 00H
	ORG $+1
$SG57845 DB	'Stack is empty', 00H
	ORG $+1
$SG57881 DB	'Stack is empty', 00H
	ORG $+1
$SG57888 DB	'Stack is empty', 00H
CONST	ENDS
PUBLIC	??0exception@std@@QEAA@QEBD@Z			; std::exception::exception
PUBLIC	??0exception@std@@QEAA@AEBV01@@Z		; std::exception::exception
PUBLIC	??1exception@std@@UEAA@XZ			; std::exception::~exception
PUBLIC	?what@exception@std@@UEBAPEBDXZ			; std::exception::what
PUBLIC	??_Gexception@std@@UEAAPEAXI@Z			; std::exception::`scalar deleting destructor'
PUBLIC	??0runtime_error@std@@QEAA@PEBD@Z		; std::runtime_error::runtime_error
PUBLIC	??1runtime_error@std@@UEAA@XZ			; std::runtime_error::~runtime_error
PUBLIC	??0runtime_error@std@@QEAA@AEBV01@@Z		; std::runtime_error::runtime_error
PUBLIC	??_Gruntime_error@std@@UEAAPEAXI@Z		; std::runtime_error::`scalar deleting destructor'
PUBLIC	?resize@?$DynamicStack@D@@AEAAXXZ		; DynamicStack<char>::resize
PUBLIC	??0?$DynamicStack@D@@QEAA@H@Z			; DynamicStack<char>::DynamicStack<char>
PUBLIC	??1?$DynamicStack@D@@QEAA@XZ			; DynamicStack<char>::~DynamicStack<char>
PUBLIC	?push@?$DynamicStack@D@@QEAAXAEBD@Z		; DynamicStack<char>::push
PUBLIC	?pop@?$DynamicStack@D@@QEAAXXZ			; DynamicStack<char>::pop
PUBLIC	?top@?$DynamicStack@D@@QEBADXZ			; DynamicStack<char>::top
PUBLIC	?isEmpty@?$DynamicStack@D@@QEBA_NXZ		; DynamicStack<char>::isEmpty
PUBLIC	?size@?$DynamicStack@D@@QEBAHXZ			; DynamicStack<char>::size
PUBLIC	??4?$DynamicStack@D@@QEAAAEAV0@AEBV0@@Z		; DynamicStack<char>::operator=
PUBLIC	??_F?$DynamicStack@D@@QEAAXXZ			; DynamicStack<char>::`default constructor closure'
PUBLIC	?resize@?$DynamicStack@H@@AEAAXXZ		; DynamicStack<int>::resize
PUBLIC	??0?$DynamicStack@H@@QEAA@H@Z			; DynamicStack<int>::DynamicStack<int>
PUBLIC	??1?$DynamicStack@H@@QEAA@XZ			; DynamicStack<int>::~DynamicStack<int>
PUBLIC	?push@?$DynamicStack@H@@QEAAXAEBH@Z		; DynamicStack<int>::push
PUBLIC	?pop@?$DynamicStack@H@@QEAAXXZ			; DynamicStack<int>::pop
PUBLIC	?top@?$DynamicStack@H@@QEBAHXZ			; DynamicStack<int>::top
PUBLIC	?isEmpty@?$DynamicStack@H@@QEBA_NXZ		; DynamicStack<int>::isEmpty
PUBLIC	?size@?$DynamicStack@H@@QEBAHXZ			; DynamicStack<int>::size
PUBLIC	??4?$DynamicStack@H@@QEAAAEAV0@AEBV0@@Z		; DynamicStack<int>::operator=
PUBLIC	??_F?$DynamicStack@H@@QEAAXXZ			; DynamicStack<int>::`default constructor closure'
PUBLIC	??0?$LinkedStack@D@@QEAA@XZ			; LinkedStack<char>::LinkedStack<char>
PUBLIC	??1?$LinkedStack@D@@QEAA@XZ			; LinkedStack<char>::~LinkedStack<char>
PUBLIC	?push@?$LinkedStack@D@@QEAAXAEBD@Z		; LinkedStack<char>::push
PUBLIC	?pop@?$LinkedStack@D@@QEAAXXZ			; LinkedStack<char>::pop
PUBLIC	?top@?$LinkedStack@D@@QEBADXZ			; LinkedStack<char>::top
PUBLIC	?isEmpty@?$LinkedStack@D@@QEBA_NXZ		; LinkedStack<char>::isEmpty
PUBLIC	?size@?$LinkedStack@D@@QEBAHXZ			; LinkedStack<char>::size
PUBLIC	??4?$LinkedStack@D@@QEAAAEAV0@AEBV0@@Z		; LinkedStack<char>::operator=
PUBLIC	??0Node@?$LinkedStack@D@@QEAA@AEBDPEAU01@@Z	; LinkedStack<char>::Node::Node
PUBLIC	??0?$LinkedStack@H@@QEAA@XZ			; LinkedStack<int>::LinkedStack<int>
PUBLIC	??1?$LinkedStack@H@@QEAA@XZ			; LinkedStack<int>::~LinkedStack<int>
PUBLIC	?push@?$LinkedStack@H@@QEAAXAEBH@Z		; LinkedStack<int>::push
PUBLIC	?pop@?$LinkedStack@H@@QEAAXXZ			; LinkedStack<int>::pop
PUBLIC	?top@?$LinkedStack@H@@QEBAHXZ			; LinkedStack<int>::top
PUBLIC	?isEmpty@?$LinkedStack@H@@QEBA_NXZ		; LinkedStack<int>::isEmpty
PUBLIC	?size@?$LinkedStack@H@@QEBAHXZ			; LinkedStack<int>::size
PUBLIC	??4?$LinkedStack@H@@QEAAAEAV0@AEBV0@@Z		; LinkedStack<int>::operator=
PUBLIC	??0Node@?$LinkedStack@H@@QEAA@AEBHPEAU01@@Z	; LinkedStack<int>::Node::Node
PUBLIC	??_7exception@std@@6B@				; std::exception::`vftable'
PUBLIC	??_C@_0BC@EOODALEL@Unknown?5exception@		; `string'
PUBLIC	??_R0?AVexception@std@@@8			; std::exception `RTTI Type Descriptor'
PUBLIC	_CT??_R0?AVexception@std@@@8??0exception@std@@QEAA@AEBV01@@Z24
PUBLIC	??_7runtime_error@std@@6B@			; std::runtime_error::`vftable'
PUBLIC	??_R0?AVruntime_error@std@@@8			; std::runtime_error `RTTI Type Descriptor'
PUBLIC	_CT??_R0?AVruntime_error@std@@@8??0runtime_error@std@@QEAA@AEBV01@@Z24
PUBLIC	_TI2?AVruntime_error@std@@
PUBLIC	_CTA2?AVruntime_error@std@@
PUBLIC	??_R4exception@std@@6B@				; std::exception::`RTTI Complete Object Locator'
PUBLIC	??_R3exception@std@@8				; std::exception::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2exception@std@@8				; std::exception::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@exception@std@@8			; std::exception::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R4runtime_error@std@@6B@			; std::runtime_error::`RTTI Complete Object Locator'
PUBLIC	??_R3runtime_error@std@@8			; std::runtime_error::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2runtime_error@std@@8			; std::runtime_error::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@runtime_error@std@@8		; std::runtime_error::`RTTI Base Class Descriptor at (0,-1,0,64)'
EXTRN	??2@YAPEAX_K@Z:PROC				; operator new
EXTRN	??3@YAXPEAX_K@Z:PROC				; operator delete
EXTRN	??_U@YAPEAX_K@Z:PROC				; operator new[]
EXTRN	??_V@YAXPEAX@Z:PROC				; operator delete[]
EXTRN	__std_exception_copy:PROC
EXTRN	__std_exception_destroy:PROC
EXTRN	??_Eexception@std@@UEAAPEAXI@Z:PROC		; std::exception::`vector deleting destructor'
EXTRN	??_Eruntime_error@std@@UEAAPEAXI@Z:PROC		; std::runtime_error::`vector deleting destructor'
EXTRN	_CxxThrowException:PROC
EXTRN	__CxxFrameHandler4:PROC
EXTRN	??_7type_info@@6B@:BYTE				; type_info::`vftable'
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0exception@std@@QEAA@QEBD@Z DD imagerel $LN4
	DD	imagerel $LN4+100
	DD	imagerel $unwind$??0exception@std@@QEAA@QEBD@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0exception@std@@QEAA@AEBV01@@Z DD imagerel $LN4
	DD	imagerel $LN4+89
	DD	imagerel $unwind$??0exception@std@@QEAA@AEBV01@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1exception@std@@UEAA@XZ DD imagerel $LN4
	DD	imagerel $LN4+47
	DD	imagerel $unwind$??1exception@std@@UEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?what@exception@std@@UEBAPEBDXZ DD imagerel $LN5
	DD	imagerel $LN5+56
	DD	imagerel $unwind$?what@exception@std@@UEBAPEBDXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??_Gexception@std@@UEAAPEAXI@Z DD imagerel $LN5
	DD	imagerel $LN5+60
	DD	imagerel $unwind$??_Gexception@std@@UEAAPEAXI@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0runtime_error@std@@QEAA@PEBD@Z DD imagerel $LN4
	DD	imagerel $LN4+54
	DD	imagerel $unwind$??0runtime_error@std@@QEAA@PEBD@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1runtime_error@std@@UEAA@XZ DD imagerel $LN4
	DD	imagerel $LN4+25
	DD	imagerel $unwind$??1runtime_error@std@@UEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0runtime_error@std@@QEAA@AEBV01@@Z DD imagerel $LN4
	DD	imagerel $LN4+54
	DD	imagerel $unwind$??0runtime_error@std@@QEAA@AEBV01@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??_Gruntime_error@std@@UEAAPEAXI@Z DD imagerel $LN5
	DD	imagerel $LN5+60
	DD	imagerel $unwind$??_Gruntime_error@std@@UEAAPEAXI@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?resize@?$DynamicStack@D@@AEAAXXZ DD imagerel $LN6
	DD	imagerel $LN6+168
	DD	imagerel $unwind$?resize@?$DynamicStack@D@@AEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0?$DynamicStack@D@@QEAA@H@Z DD imagerel $LN4
	DD	imagerel $LN4+97
	DD	imagerel $unwind$??0?$DynamicStack@D@@QEAA@H@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1?$DynamicStack@D@@QEAA@XZ DD imagerel $LN4
	DD	imagerel $LN4+38
	DD	imagerel $unwind$??1?$DynamicStack@D@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?push@?$DynamicStack@D@@QEAAXAEBD@Z DD imagerel $LN4
	DD	imagerel $LN4+134
	DD	imagerel $unwind$?push@?$DynamicStack@D@@QEAAXAEBD@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?pop@?$DynamicStack@D@@QEAAXXZ DD imagerel $LN4
	DD	imagerel $LN4+84
	DD	imagerel $unwind$?pop@?$DynamicStack@D@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?top@?$DynamicStack@D@@QEBADXZ DD imagerel $LN4
	DD	imagerel $LN4+87
	DD	imagerel $unwind$?top@?$DynamicStack@D@@QEBADXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?isEmpty@?$DynamicStack@D@@QEBA_NXZ DD imagerel $LN5
	DD	imagerel $LN5+45
	DD	imagerel $unwind$?isEmpty@?$DynamicStack@D@@QEBA_NXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??4?$DynamicStack@D@@QEAAAEAV0@AEBV0@@Z DD imagerel $LN4
	DD	imagerel $LN4+37
	DD	imagerel $unwind$??4?$DynamicStack@D@@QEAAAEAV0@AEBV0@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??_F?$DynamicStack@D@@QEAAXXZ DD imagerel $LN3
	DD	imagerel $LN3+30
	DD	imagerel $unwind$??_F?$DynamicStack@D@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?resize@?$DynamicStack@H@@AEAAXXZ DD imagerel $LN6
	DD	imagerel $LN6+196
	DD	imagerel $unwind$?resize@?$DynamicStack@H@@AEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0?$DynamicStack@H@@QEAA@H@Z DD imagerel $LN4
	DD	imagerel $LN4+126
	DD	imagerel $unwind$??0?$DynamicStack@H@@QEAA@H@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1?$DynamicStack@H@@QEAA@XZ DD imagerel $LN4
	DD	imagerel $LN4+38
	DD	imagerel $unwind$??1?$DynamicStack@H@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?push@?$DynamicStack@H@@QEAAXAEBH@Z DD imagerel $LN4
	DD	imagerel $LN4+136
	DD	imagerel $unwind$?push@?$DynamicStack@H@@QEAAXAEBH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?pop@?$DynamicStack@H@@QEAAXXZ DD imagerel $LN4
	DD	imagerel $LN4+84
	DD	imagerel $unwind$?pop@?$DynamicStack@H@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?top@?$DynamicStack@H@@QEBAHXZ DD imagerel $LN4
	DD	imagerel $LN4+86
	DD	imagerel $unwind$?top@?$DynamicStack@H@@QEBAHXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?isEmpty@?$DynamicStack@H@@QEBA_NXZ DD imagerel $LN5
	DD	imagerel $LN5+45
	DD	imagerel $unwind$?isEmpty@?$DynamicStack@H@@QEBA_NXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??4?$DynamicStack@H@@QEAAAEAV0@AEBV0@@Z DD imagerel $LN4
	DD	imagerel $LN4+37
	DD	imagerel $unwind$??4?$DynamicStack@H@@QEAAAEAV0@AEBV0@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??_F?$DynamicStack@H@@QEAAXXZ DD imagerel $LN3
	DD	imagerel $LN3+30
	DD	imagerel $unwind$??_F?$DynamicStack@H@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1?$LinkedStack@D@@QEAA@XZ DD imagerel $LN6
	DD	imagerel $LN6+44
	DD	imagerel $unwind$??1?$LinkedStack@D@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?push@?$LinkedStack@D@@QEAAXAEBD@Z DD imagerel $LN6
	DD	imagerel $LN6+132
	DD	imagerel $unwind$?push@?$LinkedStack@D@@QEAAXAEBD@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?dtor$0@?0??push@?$LinkedStack@D@@QEAAXAEBD@Z@4HA DD imagerel ?dtor$0@?0??push@?$LinkedStack@D@@QEAAXAEBD@Z@4HA
	DD	imagerel ?dtor$0@?0??push@?$LinkedStack@D@@QEAAXAEBD@Z@4HA+29
	DD	imagerel $unwind$?dtor$0@?0??push@?$LinkedStack@D@@QEAAXAEBD@Z@4HA
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?pop@?$LinkedStack@D@@QEAAXXZ DD imagerel $LN4
	DD	imagerel $LN4+143
	DD	imagerel $unwind$?pop@?$LinkedStack@D@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?top@?$LinkedStack@D@@QEBADXZ DD imagerel $LN4
	DD	imagerel $LN4+77
	DD	imagerel $unwind$?top@?$LinkedStack@D@@QEBADXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?isEmpty@?$LinkedStack@D@@QEBA_NXZ DD imagerel $LN5
	DD	imagerel $LN5+45
	DD	imagerel $unwind$?isEmpty@?$LinkedStack@D@@QEBA_NXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??4?$LinkedStack@D@@QEAAAEAV0@AEBV0@@Z DD imagerel $LN4
	DD	imagerel $LN4+37
	DD	imagerel $unwind$??4?$LinkedStack@D@@QEAAAEAV0@AEBV0@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??1?$LinkedStack@H@@QEAA@XZ DD imagerel $LN6
	DD	imagerel $LN6+44
	DD	imagerel $unwind$??1?$LinkedStack@H@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?push@?$LinkedStack@H@@QEAAXAEBH@Z DD imagerel $LN6
	DD	imagerel $LN6+132
	DD	imagerel $unwind$?push@?$LinkedStack@H@@QEAAXAEBH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?dtor$0@?0??push@?$LinkedStack@H@@QEAAXAEBH@Z@4HA DD imagerel ?dtor$0@?0??push@?$LinkedStack@H@@QEAAXAEBH@Z@4HA
	DD	imagerel ?dtor$0@?0??push@?$LinkedStack@H@@QEAAXAEBH@Z@4HA+29
	DD	imagerel $unwind$?dtor$0@?0??push@?$LinkedStack@H@@QEAAXAEBH@Z@4HA
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?pop@?$LinkedStack@H@@QEAAXXZ DD imagerel $LN4
	DD	imagerel $LN4+143
	DD	imagerel $unwind$?pop@?$LinkedStack@H@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?top@?$LinkedStack@H@@QEBAHXZ DD imagerel $LN4
	DD	imagerel $LN4+76
	DD	imagerel $unwind$?top@?$LinkedStack@H@@QEBAHXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?isEmpty@?$LinkedStack@H@@QEBA_NXZ DD imagerel $LN5
	DD	imagerel $LN5+45
	DD	imagerel $unwind$?isEmpty@?$LinkedStack@H@@QEBA_NXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??4?$LinkedStack@H@@QEAAAEAV0@AEBV0@@Z DD imagerel $LN4
	DD	imagerel $LN4+37
	DD	imagerel $unwind$??4?$LinkedStack@H@@QEAAAEAV0@AEBV0@@Z
pdata	ENDS
;	COMDAT ??_R1A@?0A@EA@runtime_error@std@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@runtime_error@std@@8 DD imagerel ??_R0?AVruntime_error@std@@@8 ; std::runtime_error::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	01H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	imagerel ??_R3runtime_error@std@@8
rdata$r	ENDS
;	COMDAT ??_R2runtime_error@std@@8
rdata$r	SEGMENT
??_R2runtime_error@std@@8 DD imagerel ??_R1A@?0A@EA@runtime_error@std@@8 ; std::runtime_error::`RTTI Base Class Array'
	DD	imagerel ??_R1A@?0A@EA@exception@std@@8
	ORG $+3
rdata$r	ENDS
;	COMDAT ??_R3runtime_error@std@@8
rdata$r	SEGMENT
??_R3runtime_error@std@@8 DD 00H			; std::runtime_error::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	02H
	DD	imagerel ??_R2runtime_error@std@@8
rdata$r	ENDS
;	COMDAT ??_R4runtime_error@std@@6B@
rdata$r	SEGMENT
??_R4runtime_error@std@@6B@ DD 01H			; std::runtime_error::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	imagerel ??_R0?AVruntime_error@std@@@8
	DD	imagerel ??_R3runtime_error@std@@8
	DD	imagerel ??_R4runtime_error@std@@6B@
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@exception@std@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@exception@std@@8 DD imagerel ??_R0?AVexception@std@@@8 ; std::exception::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	00H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	imagerel ??_R3exception@std@@8
rdata$r	ENDS
;	COMDAT ??_R2exception@std@@8
rdata$r	SEGMENT
??_R2exception@std@@8 DD imagerel ??_R1A@?0A@EA@exception@std@@8 ; std::exception::`RTTI Base Class Array'
	ORG $+3
rdata$r	ENDS
;	COMDAT ??_R3exception@std@@8
rdata$r	SEGMENT
??_R3exception@std@@8 DD 00H				; std::exception::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	01H
	DD	imagerel ??_R2exception@std@@8
rdata$r	ENDS
;	COMDAT ??_R4exception@std@@6B@
rdata$r	SEGMENT
??_R4exception@std@@6B@ DD 01H				; std::exception::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	imagerel ??_R0?AVexception@std@@@8
	DD	imagerel ??_R3exception@std@@8
	DD	imagerel ??_R4exception@std@@6B@
rdata$r	ENDS
;	COMDAT _CTA2?AVruntime_error@std@@
xdata$x	SEGMENT
_CTA2?AVruntime_error@std@@ DD 02H
	DD	imagerel _CT??_R0?AVruntime_error@std@@@8??0runtime_error@std@@QEAA@AEBV01@@Z24
	DD	imagerel _CT??_R0?AVexception@std@@@8??0exception@std@@QEAA@AEBV01@@Z24
xdata$x	ENDS
;	COMDAT _TI2?AVruntime_error@std@@
xdata$x	SEGMENT
_TI2?AVruntime_error@std@@ DD 00H
	DD	imagerel ??1runtime_error@std@@UEAA@XZ
	DD	00H
	DD	imagerel _CTA2?AVruntime_error@std@@
xdata$x	ENDS
;	COMDAT _CT??_R0?AVruntime_error@std@@@8??0runtime_error@std@@QEAA@AEBV01@@Z24
xdata$x	SEGMENT
_CT??_R0?AVruntime_error@std@@@8??0runtime_error@std@@QEAA@AEBV01@@Z24 DD 00H
	DD	imagerel ??_R0?AVruntime_error@std@@@8
	DD	00H
	DD	0ffffffffH
	ORG $+4
	DD	018H
	DD	imagerel ??0runtime_error@std@@QEAA@AEBV01@@Z
xdata$x	ENDS
;	COMDAT ??_R0?AVruntime_error@std@@@8
data$r	SEGMENT
??_R0?AVruntime_error@std@@@8 DQ FLAT:??_7type_info@@6B@ ; std::runtime_error `RTTI Type Descriptor'
	DQ	0000000000000000H
	DB	'.?AVruntime_error@std@@', 00H
data$r	ENDS
;	COMDAT ??_7runtime_error@std@@6B@
CONST	SEGMENT
??_7runtime_error@std@@6B@ DQ FLAT:??_R4runtime_error@std@@6B@ ; std::runtime_error::`vftable'
	DQ	FLAT:??_Eruntime_error@std@@UEAAPEAXI@Z
	DQ	FLAT:?what@exception@std@@UEBAPEBDXZ
CONST	ENDS
;	COMDAT _CT??_R0?AVexception@std@@@8??0exception@std@@QEAA@AEBV01@@Z24
xdata$x	SEGMENT
_CT??_R0?AVexception@std@@@8??0exception@std@@QEAA@AEBV01@@Z24 DD 00H
	DD	imagerel ??_R0?AVexception@std@@@8
	DD	00H
	DD	0ffffffffH
	ORG $+4
	DD	018H
	DD	imagerel ??0exception@std@@QEAA@AEBV01@@Z
xdata$x	ENDS
;	COMDAT ??_R0?AVexception@std@@@8
data$r	SEGMENT
??_R0?AVexception@std@@@8 DQ FLAT:??_7type_info@@6B@	; std::exception `RTTI Type Descriptor'
	DQ	0000000000000000H
	DB	'.?AVexception@std@@', 00H
data$r	ENDS
;	COMDAT ??_C@_0BC@EOODALEL@Unknown?5exception@
CONST	SEGMENT
??_C@_0BC@EOODALEL@Unknown?5exception@ DB 'Unknown exception', 00H ; `string'
CONST	ENDS
;	COMDAT ??_7exception@std@@6B@
CONST	SEGMENT
??_7exception@std@@6B@ DQ FLAT:??_R4exception@std@@6B@	; std::exception::`vftable'
	DQ	FLAT:??_Eexception@std@@UEAAPEAXI@Z
	DQ	FLAT:?what@exception@std@@UEBAPEBDXZ
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??4?$LinkedStack@H@@QEAAAEAV0@AEBV0@@Z DD 020c01H
	DD	0600b700cH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?isEmpty@?$LinkedStack@H@@QEBA_NXZ DD 010901H
	DD	02209H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?top@?$LinkedStack@H@@QEBAHXZ DD 010901H
	DD	08209H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?pop@?$LinkedStack@H@@QEAAXXZ DD 010901H
	DD	0a209H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?dtor$0@?0??push@?$LinkedStack@H@@QEAAXAEBH@Z@4HA DD 020601H
	DD	050023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$?push@?$LinkedStack@H@@QEAAXAEBH@Z DB 06H
	DB	00H
	DB	00H
	DB	':'
	DB	02H
	DB	'r'
	DB	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$?push@?$LinkedStack@H@@QEAAXAEBH@Z DB 02H
	DB	0eH
	DD	imagerel ?dtor$0@?0??push@?$LinkedStack@H@@QEAAXAEBH@Z@4HA
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$?push@?$LinkedStack@H@@QEAAXAEBH@Z DB 028H
	DD	imagerel $stateUnwindMap$?push@?$LinkedStack@H@@QEAAXAEBH@Z
	DD	imagerel $ip2state$?push@?$LinkedStack@H@@QEAAXAEBH@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?push@?$LinkedStack@H@@QEAAXAEBH@Z DD 010e11H
	DD	0820eH
	DD	imagerel __CxxFrameHandler4
	DD	imagerel $cppxdata$?push@?$LinkedStack@H@@QEAAXAEBH@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$??1?$LinkedStack@H@@QEAA@XZ DB 02H
	DB	00H
	DB	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$??1?$LinkedStack@H@@QEAA@XZ DB 060H
	DD	imagerel $ip2state$??1?$LinkedStack@H@@QEAA@XZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1?$LinkedStack@H@@QEAA@XZ DD 010919H
	DD	04209H
	DD	imagerel __CxxFrameHandler4
	DD	imagerel $cppxdata$??1?$LinkedStack@H@@QEAA@XZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??4?$LinkedStack@D@@QEAAAEAV0@AEBV0@@Z DD 020c01H
	DD	0600b700cH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?isEmpty@?$LinkedStack@D@@QEBA_NXZ DD 010901H
	DD	02209H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?top@?$LinkedStack@D@@QEBADXZ DD 010901H
	DD	08209H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?pop@?$LinkedStack@D@@QEAAXXZ DD 010901H
	DD	0a209H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?dtor$0@?0??push@?$LinkedStack@D@@QEAAXAEBD@Z@4HA DD 020601H
	DD	050023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$?push@?$LinkedStack@D@@QEAAXAEBD@Z DB 06H
	DB	00H
	DB	00H
	DB	':'
	DB	02H
	DB	'r'
	DB	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$?push@?$LinkedStack@D@@QEAAXAEBD@Z DB 02H
	DB	0eH
	DD	imagerel ?dtor$0@?0??push@?$LinkedStack@D@@QEAAXAEBD@Z@4HA
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$?push@?$LinkedStack@D@@QEAAXAEBD@Z DB 028H
	DD	imagerel $stateUnwindMap$?push@?$LinkedStack@D@@QEAAXAEBD@Z
	DD	imagerel $ip2state$?push@?$LinkedStack@D@@QEAAXAEBD@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?push@?$LinkedStack@D@@QEAAXAEBD@Z DD 010e11H
	DD	0820eH
	DD	imagerel __CxxFrameHandler4
	DD	imagerel $cppxdata$?push@?$LinkedStack@D@@QEAAXAEBD@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$??1?$LinkedStack@D@@QEAA@XZ DB 02H
	DB	00H
	DB	00H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$cppxdata$??1?$LinkedStack@D@@QEAA@XZ DB 060H
	DD	imagerel $ip2state$??1?$LinkedStack@D@@QEAA@XZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1?$LinkedStack@D@@QEAA@XZ DD 010919H
	DD	04209H
	DD	imagerel __CxxFrameHandler4
	DD	imagerel $cppxdata$??1?$LinkedStack@D@@QEAA@XZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??_F?$DynamicStack@H@@QEAAXXZ DD 010901H
	DD	04209H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??4?$DynamicStack@H@@QEAAAEAV0@AEBV0@@Z DD 020c01H
	DD	0600b700cH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?isEmpty@?$DynamicStack@H@@QEBA_NXZ DD 010901H
	DD	02209H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?top@?$DynamicStack@H@@QEBAHXZ DD 010901H
	DD	08209H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?pop@?$DynamicStack@H@@QEAAXXZ DD 010901H
	DD	08209H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?push@?$DynamicStack@H@@QEAAXAEBH@Z DD 010e01H
	DD	0820eH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1?$DynamicStack@H@@QEAA@XZ DD 010901H
	DD	06209H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0?$DynamicStack@H@@QEAA@H@Z DD 010d01H
	DD	0620dH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?resize@?$DynamicStack@H@@AEAAXXZ DD 010901H
	DD	0a209H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??_F?$DynamicStack@D@@QEAAXXZ DD 010901H
	DD	04209H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??4?$DynamicStack@D@@QEAAAEAV0@AEBV0@@Z DD 020c01H
	DD	0600b700cH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?isEmpty@?$DynamicStack@D@@QEBA_NXZ DD 010901H
	DD	02209H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?top@?$DynamicStack@D@@QEBADXZ DD 010901H
	DD	08209H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?pop@?$DynamicStack@D@@QEAAXXZ DD 010901H
	DD	08209H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?push@?$DynamicStack@D@@QEAAXAEBD@Z DD 010e01H
	DD	0820eH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1?$DynamicStack@D@@QEAA@XZ DD 010901H
	DD	06209H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0?$DynamicStack@D@@QEAA@H@Z DD 010d01H
	DD	0620dH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?resize@?$DynamicStack@D@@AEAAXXZ DD 010901H
	DD	08209H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??_Gruntime_error@std@@UEAAPEAXI@Z DD 010d01H
	DD	0420dH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0runtime_error@std@@QEAA@AEBV01@@Z DD 010e01H
	DD	0420eH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1runtime_error@std@@UEAA@XZ DD 010901H
	DD	04209H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0runtime_error@std@@QEAA@PEBD@Z DD 010e01H
	DD	0420eH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??_Gexception@std@@UEAAPEAXI@Z DD 010d01H
	DD	0420dH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?what@exception@std@@UEBAPEBDXZ DD 010901H
	DD	02209H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??1exception@std@@UEAA@XZ DD 010901H
	DD	04209H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0exception@std@@QEAA@AEBV01@@Z DD 020f01H
	DD	0700b320fH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0exception@std@@QEAA@QEBD@Z DD 020f01H
	DD	0700b520fH
xdata	ENDS
; Function compile flags: /Odtp
; File C:\Users\youss\OneDrive\Documents\ILISI 2\2026 Cpp Avance et Virtualisation\TPs\TP1\StackDLL_Project\Stack.h
;	COMDAT ??0Node@?$LinkedStack@H@@QEAA@AEBHPEAU01@@Z
_TEXT	SEGMENT
this$ = 8
value$ = 16
nextNode$ = 24
??0Node@?$LinkedStack@H@@QEAA@AEBHPEAU01@@Z PROC	; LinkedStack<int>::Node::Node, COMDAT

; 62   :         {

	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx

; 61   :             : data(value), next(nextNode)

	mov	rax, QWORD PTR this$[rsp]
	mov	rcx, QWORD PTR value$[rsp]
	mov	ecx, DWORD PTR [rcx]
	mov	DWORD PTR [rax], ecx
	mov	rax, QWORD PTR this$[rsp]
	mov	rcx, QWORD PTR nextNode$[rsp]
	mov	QWORD PTR [rax+8], rcx

; 63   :         }

	mov	rax, QWORD PTR this$[rsp]
	ret	0
??0Node@?$LinkedStack@H@@QEAA@AEBHPEAU01@@Z ENDP	; LinkedStack<int>::Node::Node
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??4?$LinkedStack@H@@QEAAAEAV0@AEBV0@@Z
_TEXT	SEGMENT
this$ = 24
__that$ = 32
??4?$LinkedStack@H@@QEAAAEAV0@AEBV0@@Z PROC		; LinkedStack<int>::operator=, COMDAT
$LN4:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rsi
	push	rdi
	mov	rdi, QWORD PTR this$[rsp]
	mov	rsi, QWORD PTR __that$[rsp]
	mov	ecx, 16
	rep movsb
	mov	rax, QWORD PTR this$[rsp]
	pop	rdi
	pop	rsi
	ret	0
??4?$LinkedStack@H@@QEAAAEAV0@AEBV0@@Z ENDP		; LinkedStack<int>::operator=
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\youss\OneDrive\Documents\ILISI 2\2026 Cpp Avance et Virtualisation\TPs\TP1\StackDLL_Project\Stack.cpp
;	COMDAT ?size@?$LinkedStack@H@@QEBAHXZ
_TEXT	SEGMENT
this$ = 8
?size@?$LinkedStack@H@@QEBAHXZ PROC			; LinkedStack<int>::size, COMDAT

; 165  : {

	mov	QWORD PTR [rsp+8], rcx

; 166  :     return count;

	mov	rax, QWORD PTR this$[rsp]
	mov	eax, DWORD PTR [rax+8]

; 167  : }

	ret	0
?size@?$LinkedStack@H@@QEBAHXZ ENDP			; LinkedStack<int>::size
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\youss\OneDrive\Documents\ILISI 2\2026 Cpp Avance et Virtualisation\TPs\TP1\StackDLL_Project\Stack.cpp
;	COMDAT ?isEmpty@?$LinkedStack@H@@QEBA_NXZ
_TEXT	SEGMENT
tv66 = 0
this$ = 32
?isEmpty@?$LinkedStack@H@@QEBA_NXZ PROC			; LinkedStack<int>::isEmpty, COMDAT

; 158  : {

$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 24

; 159  :     return topNode == nullptr;

	mov	rax, QWORD PTR this$[rsp]
	cmp	QWORD PTR [rax], 0
	jne	SHORT $LN3@isEmpty
	mov	DWORD PTR tv66[rsp], 1
	jmp	SHORT $LN4@isEmpty
$LN3@isEmpty:
	mov	DWORD PTR tv66[rsp], 0
$LN4@isEmpty:
	movzx	eax, BYTE PTR tv66[rsp]

; 160  : }

	add	rsp, 24
	ret	0
?isEmpty@?$LinkedStack@H@@QEBA_NXZ ENDP			; LinkedStack<int>::isEmpty
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\youss\OneDrive\Documents\ILISI 2\2026 Cpp Avance et Virtualisation\TPs\TP1\StackDLL_Project\Stack.cpp
;	COMDAT ?top@?$LinkedStack@H@@QEBAHXZ
_TEXT	SEGMENT
$T1 = 32
this$ = 80
?top@?$LinkedStack@H@@QEBAHXZ PROC			; LinkedStack<int>::top, COMDAT

; 146  : {

$LN4:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 72					; 00000048H

; 147  :     if (isEmpty())

	mov	rcx, QWORD PTR this$[rsp]
	call	?isEmpty@?$LinkedStack@H@@QEBA_NXZ	; LinkedStack<int>::isEmpty
	movzx	eax, al
	test	eax, eax
	je	SHORT $LN2@top

; 148  :     {
; 149  :         throw std::runtime_error("Stack is empty");

	lea	rdx, OFFSET FLAT:$SG57888
	lea	rcx, QWORD PTR $T1[rsp]
	call	??0runtime_error@std@@QEAA@PEBD@Z	; std::runtime_error::runtime_error
	lea	rdx, OFFSET FLAT:_TI2?AVruntime_error@std@@
	lea	rcx, QWORD PTR $T1[rsp]
	call	_CxxThrowException
	npad	1
$LN2@top:

; 150  :     }
; 151  : 
; 152  :     return topNode->data;

	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	eax, DWORD PTR [rax]
$LN3@top:

; 153  : }

	add	rsp, 72					; 00000048H
	ret	0
?top@?$LinkedStack@H@@QEBAHXZ ENDP			; LinkedStack<int>::top
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\youss\OneDrive\Documents\ILISI 2\2026 Cpp Avance et Virtualisation\TPs\TP1\StackDLL_Project\Stack.cpp
;	COMDAT ?pop@?$LinkedStack@H@@QEAAXXZ
_TEXT	SEGMENT
temp$ = 32
$T1 = 40
$T2 = 48
this$ = 96
?pop@?$LinkedStack@H@@QEAAXXZ PROC			; LinkedStack<int>::pop, COMDAT

; 128  : {

$LN4:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 88					; 00000058H

; 129  :     if (isEmpty())

	mov	rcx, QWORD PTR this$[rsp]
	call	?isEmpty@?$LinkedStack@H@@QEBA_NXZ	; LinkedStack<int>::isEmpty
	movzx	eax, al
	test	eax, eax
	je	SHORT $LN2@pop

; 130  :     {
; 131  :         throw std::runtime_error("Stack is empty");

	lea	rdx, OFFSET FLAT:$SG57881
	lea	rcx, QWORD PTR $T2[rsp]
	call	??0runtime_error@std@@QEAA@PEBD@Z	; std::runtime_error::runtime_error
	lea	rdx, OFFSET FLAT:_TI2?AVruntime_error@std@@
	lea	rcx, QWORD PTR $T2[rsp]
	call	_CxxThrowException
	npad	1
$LN2@pop:

; 132  :     }
; 133  : 
; 134  :     Node* temp = topNode;

	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	QWORD PTR temp$[rsp], rax

; 135  : 
; 136  :     topNode = topNode->next;

	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	rcx, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax+8]
	mov	QWORD PTR [rcx], rax

; 137  : 
; 138  :     delete temp;

	mov	rax, QWORD PTR temp$[rsp]
	mov	QWORD PTR $T1[rsp], rax
	mov	edx, 16
	mov	rcx, QWORD PTR $T1[rsp]
	call	??3@YAXPEAX_K@Z				; operator delete
	npad	1

; 139  : 
; 140  :     count--;

	mov	rax, QWORD PTR this$[rsp]
	mov	eax, DWORD PTR [rax+8]
	dec	eax
	mov	rcx, QWORD PTR this$[rsp]
	mov	DWORD PTR [rcx+8], eax
$LN3@pop:

; 141  : }

	add	rsp, 88					; 00000058H
	ret	0
?pop@?$LinkedStack@H@@QEAAXXZ ENDP			; LinkedStack<int>::pop
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\youss\OneDrive\Documents\ILISI 2\2026 Cpp Avance et Virtualisation\TPs\TP1\StackDLL_Project\Stack.cpp
;	COMDAT ?push@?$LinkedStack@H@@QEAAXAEBH@Z
_TEXT	SEGMENT
$T1 = 32
tv78 = 40
$T2 = 48
newNode$ = 56
this$ = 80
value$ = 88
?push@?$LinkedStack@H@@QEAAXAEBH@Z PROC			; LinkedStack<int>::push, COMDAT

; 118  : {

$LN6:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 72					; 00000048H

; 119  :     Node* newNode = new Node(value, topNode);

	mov	ecx, 16
	call	??2@YAPEAX_K@Z				; operator new
	mov	QWORD PTR $T1[rsp], rax
	cmp	QWORD PTR $T1[rsp], 0
	je	SHORT $LN3@push
	mov	rax, QWORD PTR this$[rsp]
	mov	r8, QWORD PTR [rax]
	mov	rdx, QWORD PTR value$[rsp]
	mov	rcx, QWORD PTR $T1[rsp]
	call	??0Node@?$LinkedStack@H@@QEAA@AEBHPEAU01@@Z ; LinkedStack<int>::Node::Node
	mov	QWORD PTR tv78[rsp], rax
	jmp	SHORT $LN4@push
$LN3@push:
	mov	QWORD PTR tv78[rsp], 0
$LN4@push:
	mov	rax, QWORD PTR tv78[rsp]
	mov	QWORD PTR $T2[rsp], rax
	mov	rax, QWORD PTR $T2[rsp]
	mov	QWORD PTR newNode$[rsp], rax

; 120  : 
; 121  :     topNode = newNode;

	mov	rax, QWORD PTR this$[rsp]
	mov	rcx, QWORD PTR newNode$[rsp]
	mov	QWORD PTR [rax], rcx

; 122  :     count++;

	mov	rax, QWORD PTR this$[rsp]
	mov	eax, DWORD PTR [rax+8]
	inc	eax
	mov	rcx, QWORD PTR this$[rsp]
	mov	DWORD PTR [rcx+8], eax

; 123  : }

	add	rsp, 72					; 00000048H
	ret	0
?push@?$LinkedStack@H@@QEAAXAEBH@Z ENDP			; LinkedStack<int>::push
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT text$x
text$x	SEGMENT
$T1 = 32
tv78 = 40
$T2 = 48
newNode$ = 56
this$ = 80
value$ = 88
?dtor$0@?0??push@?$LinkedStack@H@@QEAAXAEBH@Z@4HA PROC	; `LinkedStack<int>::push'::`1'::dtor$0
	push	rbp
	sub	rsp, 32					; 00000020H
	mov	rbp, rdx
	mov	edx, 16
	mov	rcx, QWORD PTR $T1[rbp]
	call	??3@YAXPEAX_K@Z				; operator delete
	add	rsp, 32					; 00000020H
	pop	rbp
	ret	0
?dtor$0@?0??push@?$LinkedStack@H@@QEAAXAEBH@Z@4HA ENDP	; `LinkedStack<int>::push'::`1'::dtor$0
text$x	ENDS
; Function compile flags: /Odtp
; File C:\Users\youss\OneDrive\Documents\ILISI 2\2026 Cpp Avance et Virtualisation\TPs\TP1\StackDLL_Project\Stack.cpp
;	COMDAT ??1?$LinkedStack@H@@QEAA@XZ
_TEXT	SEGMENT
this$ = 48
??1?$LinkedStack@H@@QEAA@XZ PROC			; LinkedStack<int>::~LinkedStack<int>, COMDAT

; 108  : {

$LN6:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
$LN2@LinkedStac:

; 109  :     while (!isEmpty())

	mov	rcx, QWORD PTR this$[rsp]
	call	?isEmpty@?$LinkedStack@H@@QEBA_NXZ	; LinkedStack<int>::isEmpty
	movzx	eax, al
	test	eax, eax
	jne	SHORT $LN3@LinkedStac

; 110  :     {
; 111  :         pop();

	mov	rcx, QWORD PTR this$[rsp]
	call	?pop@?$LinkedStack@H@@QEAAXXZ		; LinkedStack<int>::pop
	npad	1

; 112  :     }

	jmp	SHORT $LN2@LinkedStac
$LN3@LinkedStac:

; 113  : }

	add	rsp, 40					; 00000028H
	ret	0
??1?$LinkedStack@H@@QEAA@XZ ENDP			; LinkedStack<int>::~LinkedStack<int>
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\youss\OneDrive\Documents\ILISI 2\2026 Cpp Avance et Virtualisation\TPs\TP1\StackDLL_Project\Stack.cpp
;	COMDAT ??0?$LinkedStack@H@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??0?$LinkedStack@H@@QEAA@XZ PROC			; LinkedStack<int>::LinkedStack<int>, COMDAT

; 100  : {

	mov	QWORD PTR [rsp+8], rcx

; 101  :     topNode = nullptr;

	mov	rax, QWORD PTR this$[rsp]
	mov	QWORD PTR [rax], 0

; 102  :     count = 0;

	mov	rax, QWORD PTR this$[rsp]
	mov	DWORD PTR [rax+8], 0

; 103  : }

	mov	rax, QWORD PTR this$[rsp]
	ret	0
??0?$LinkedStack@H@@QEAA@XZ ENDP			; LinkedStack<int>::LinkedStack<int>
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\youss\OneDrive\Documents\ILISI 2\2026 Cpp Avance et Virtualisation\TPs\TP1\StackDLL_Project\Stack.h
;	COMDAT ??0Node@?$LinkedStack@D@@QEAA@AEBDPEAU01@@Z
_TEXT	SEGMENT
this$ = 8
value$ = 16
nextNode$ = 24
??0Node@?$LinkedStack@D@@QEAA@AEBDPEAU01@@Z PROC	; LinkedStack<char>::Node::Node, COMDAT

; 62   :         {

	mov	QWORD PTR [rsp+24], r8
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx

; 61   :             : data(value), next(nextNode)

	mov	rax, QWORD PTR this$[rsp]
	mov	rcx, QWORD PTR value$[rsp]
	movzx	ecx, BYTE PTR [rcx]
	mov	BYTE PTR [rax], cl
	mov	rax, QWORD PTR this$[rsp]
	mov	rcx, QWORD PTR nextNode$[rsp]
	mov	QWORD PTR [rax+8], rcx

; 63   :         }

	mov	rax, QWORD PTR this$[rsp]
	ret	0
??0Node@?$LinkedStack@D@@QEAA@AEBDPEAU01@@Z ENDP	; LinkedStack<char>::Node::Node
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??4?$LinkedStack@D@@QEAAAEAV0@AEBV0@@Z
_TEXT	SEGMENT
this$ = 24
__that$ = 32
??4?$LinkedStack@D@@QEAAAEAV0@AEBV0@@Z PROC		; LinkedStack<char>::operator=, COMDAT
$LN4:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rsi
	push	rdi
	mov	rdi, QWORD PTR this$[rsp]
	mov	rsi, QWORD PTR __that$[rsp]
	mov	ecx, 16
	rep movsb
	mov	rax, QWORD PTR this$[rsp]
	pop	rdi
	pop	rsi
	ret	0
??4?$LinkedStack@D@@QEAAAEAV0@AEBV0@@Z ENDP		; LinkedStack<char>::operator=
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\youss\OneDrive\Documents\ILISI 2\2026 Cpp Avance et Virtualisation\TPs\TP1\StackDLL_Project\Stack.cpp
;	COMDAT ?size@?$LinkedStack@D@@QEBAHXZ
_TEXT	SEGMENT
this$ = 8
?size@?$LinkedStack@D@@QEBAHXZ PROC			; LinkedStack<char>::size, COMDAT

; 165  : {

	mov	QWORD PTR [rsp+8], rcx

; 166  :     return count;

	mov	rax, QWORD PTR this$[rsp]
	mov	eax, DWORD PTR [rax+8]

; 167  : }

	ret	0
?size@?$LinkedStack@D@@QEBAHXZ ENDP			; LinkedStack<char>::size
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\youss\OneDrive\Documents\ILISI 2\2026 Cpp Avance et Virtualisation\TPs\TP1\StackDLL_Project\Stack.cpp
;	COMDAT ?isEmpty@?$LinkedStack@D@@QEBA_NXZ
_TEXT	SEGMENT
tv66 = 0
this$ = 32
?isEmpty@?$LinkedStack@D@@QEBA_NXZ PROC			; LinkedStack<char>::isEmpty, COMDAT

; 158  : {

$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 24

; 159  :     return topNode == nullptr;

	mov	rax, QWORD PTR this$[rsp]
	cmp	QWORD PTR [rax], 0
	jne	SHORT $LN3@isEmpty
	mov	DWORD PTR tv66[rsp], 1
	jmp	SHORT $LN4@isEmpty
$LN3@isEmpty:
	mov	DWORD PTR tv66[rsp], 0
$LN4@isEmpty:
	movzx	eax, BYTE PTR tv66[rsp]

; 160  : }

	add	rsp, 24
	ret	0
?isEmpty@?$LinkedStack@D@@QEBA_NXZ ENDP			; LinkedStack<char>::isEmpty
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\youss\OneDrive\Documents\ILISI 2\2026 Cpp Avance et Virtualisation\TPs\TP1\StackDLL_Project\Stack.cpp
;	COMDAT ?top@?$LinkedStack@D@@QEBADXZ
_TEXT	SEGMENT
$T1 = 32
this$ = 80
?top@?$LinkedStack@D@@QEBADXZ PROC			; LinkedStack<char>::top, COMDAT

; 146  : {

$LN4:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 72					; 00000048H

; 147  :     if (isEmpty())

	mov	rcx, QWORD PTR this$[rsp]
	call	?isEmpty@?$LinkedStack@D@@QEBA_NXZ	; LinkedStack<char>::isEmpty
	movzx	eax, al
	test	eax, eax
	je	SHORT $LN2@top

; 148  :     {
; 149  :         throw std::runtime_error("Stack is empty");

	lea	rdx, OFFSET FLAT:$SG57845
	lea	rcx, QWORD PTR $T1[rsp]
	call	??0runtime_error@std@@QEAA@PEBD@Z	; std::runtime_error::runtime_error
	lea	rdx, OFFSET FLAT:_TI2?AVruntime_error@std@@
	lea	rcx, QWORD PTR $T1[rsp]
	call	_CxxThrowException
	npad	1
$LN2@top:

; 150  :     }
; 151  : 
; 152  :     return topNode->data;

	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
	movzx	eax, BYTE PTR [rax]
$LN3@top:

; 153  : }

	add	rsp, 72					; 00000048H
	ret	0
?top@?$LinkedStack@D@@QEBADXZ ENDP			; LinkedStack<char>::top
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\youss\OneDrive\Documents\ILISI 2\2026 Cpp Avance et Virtualisation\TPs\TP1\StackDLL_Project\Stack.cpp
;	COMDAT ?pop@?$LinkedStack@D@@QEAAXXZ
_TEXT	SEGMENT
temp$ = 32
$T1 = 40
$T2 = 48
this$ = 96
?pop@?$LinkedStack@D@@QEAAXXZ PROC			; LinkedStack<char>::pop, COMDAT

; 128  : {

$LN4:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 88					; 00000058H

; 129  :     if (isEmpty())

	mov	rcx, QWORD PTR this$[rsp]
	call	?isEmpty@?$LinkedStack@D@@QEBA_NXZ	; LinkedStack<char>::isEmpty
	movzx	eax, al
	test	eax, eax
	je	SHORT $LN2@pop

; 130  :     {
; 131  :         throw std::runtime_error("Stack is empty");

	lea	rdx, OFFSET FLAT:$SG57838
	lea	rcx, QWORD PTR $T2[rsp]
	call	??0runtime_error@std@@QEAA@PEBD@Z	; std::runtime_error::runtime_error
	lea	rdx, OFFSET FLAT:_TI2?AVruntime_error@std@@
	lea	rcx, QWORD PTR $T2[rsp]
	call	_CxxThrowException
	npad	1
$LN2@pop:

; 132  :     }
; 133  : 
; 134  :     Node* temp = topNode;

	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	QWORD PTR temp$[rsp], rax

; 135  : 
; 136  :     topNode = topNode->next;

	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	rcx, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax+8]
	mov	QWORD PTR [rcx], rax

; 137  : 
; 138  :     delete temp;

	mov	rax, QWORD PTR temp$[rsp]
	mov	QWORD PTR $T1[rsp], rax
	mov	edx, 16
	mov	rcx, QWORD PTR $T1[rsp]
	call	??3@YAXPEAX_K@Z				; operator delete
	npad	1

; 139  : 
; 140  :     count--;

	mov	rax, QWORD PTR this$[rsp]
	mov	eax, DWORD PTR [rax+8]
	dec	eax
	mov	rcx, QWORD PTR this$[rsp]
	mov	DWORD PTR [rcx+8], eax
$LN3@pop:

; 141  : }

	add	rsp, 88					; 00000058H
	ret	0
?pop@?$LinkedStack@D@@QEAAXXZ ENDP			; LinkedStack<char>::pop
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\youss\OneDrive\Documents\ILISI 2\2026 Cpp Avance et Virtualisation\TPs\TP1\StackDLL_Project\Stack.cpp
;	COMDAT ?push@?$LinkedStack@D@@QEAAXAEBD@Z
_TEXT	SEGMENT
$T1 = 32
tv78 = 40
$T2 = 48
newNode$ = 56
this$ = 80
value$ = 88
?push@?$LinkedStack@D@@QEAAXAEBD@Z PROC			; LinkedStack<char>::push, COMDAT

; 118  : {

$LN6:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 72					; 00000048H

; 119  :     Node* newNode = new Node(value, topNode);

	mov	ecx, 16
	call	??2@YAPEAX_K@Z				; operator new
	mov	QWORD PTR $T1[rsp], rax
	cmp	QWORD PTR $T1[rsp], 0
	je	SHORT $LN3@push
	mov	rax, QWORD PTR this$[rsp]
	mov	r8, QWORD PTR [rax]
	mov	rdx, QWORD PTR value$[rsp]
	mov	rcx, QWORD PTR $T1[rsp]
	call	??0Node@?$LinkedStack@D@@QEAA@AEBDPEAU01@@Z ; LinkedStack<char>::Node::Node
	mov	QWORD PTR tv78[rsp], rax
	jmp	SHORT $LN4@push
$LN3@push:
	mov	QWORD PTR tv78[rsp], 0
$LN4@push:
	mov	rax, QWORD PTR tv78[rsp]
	mov	QWORD PTR $T2[rsp], rax
	mov	rax, QWORD PTR $T2[rsp]
	mov	QWORD PTR newNode$[rsp], rax

; 120  : 
; 121  :     topNode = newNode;

	mov	rax, QWORD PTR this$[rsp]
	mov	rcx, QWORD PTR newNode$[rsp]
	mov	QWORD PTR [rax], rcx

; 122  :     count++;

	mov	rax, QWORD PTR this$[rsp]
	mov	eax, DWORD PTR [rax+8]
	inc	eax
	mov	rcx, QWORD PTR this$[rsp]
	mov	DWORD PTR [rcx+8], eax

; 123  : }

	add	rsp, 72					; 00000048H
	ret	0
?push@?$LinkedStack@D@@QEAAXAEBD@Z ENDP			; LinkedStack<char>::push
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT text$x
text$x	SEGMENT
$T1 = 32
tv78 = 40
$T2 = 48
newNode$ = 56
this$ = 80
value$ = 88
?dtor$0@?0??push@?$LinkedStack@D@@QEAAXAEBD@Z@4HA PROC	; `LinkedStack<char>::push'::`1'::dtor$0
	push	rbp
	sub	rsp, 32					; 00000020H
	mov	rbp, rdx
	mov	edx, 16
	mov	rcx, QWORD PTR $T1[rbp]
	call	??3@YAXPEAX_K@Z				; operator delete
	add	rsp, 32					; 00000020H
	pop	rbp
	ret	0
?dtor$0@?0??push@?$LinkedStack@D@@QEAAXAEBD@Z@4HA ENDP	; `LinkedStack<char>::push'::`1'::dtor$0
text$x	ENDS
; Function compile flags: /Odtp
; File C:\Users\youss\OneDrive\Documents\ILISI 2\2026 Cpp Avance et Virtualisation\TPs\TP1\StackDLL_Project\Stack.cpp
;	COMDAT ??1?$LinkedStack@D@@QEAA@XZ
_TEXT	SEGMENT
this$ = 48
??1?$LinkedStack@D@@QEAA@XZ PROC			; LinkedStack<char>::~LinkedStack<char>, COMDAT

; 108  : {

$LN6:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
$LN2@LinkedStac:

; 109  :     while (!isEmpty())

	mov	rcx, QWORD PTR this$[rsp]
	call	?isEmpty@?$LinkedStack@D@@QEBA_NXZ	; LinkedStack<char>::isEmpty
	movzx	eax, al
	test	eax, eax
	jne	SHORT $LN3@LinkedStac

; 110  :     {
; 111  :         pop();

	mov	rcx, QWORD PTR this$[rsp]
	call	?pop@?$LinkedStack@D@@QEAAXXZ		; LinkedStack<char>::pop
	npad	1

; 112  :     }

	jmp	SHORT $LN2@LinkedStac
$LN3@LinkedStac:

; 113  : }

	add	rsp, 40					; 00000028H
	ret	0
??1?$LinkedStack@D@@QEAA@XZ ENDP			; LinkedStack<char>::~LinkedStack<char>
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\youss\OneDrive\Documents\ILISI 2\2026 Cpp Avance et Virtualisation\TPs\TP1\StackDLL_Project\Stack.cpp
;	COMDAT ??0?$LinkedStack@D@@QEAA@XZ
_TEXT	SEGMENT
this$ = 8
??0?$LinkedStack@D@@QEAA@XZ PROC			; LinkedStack<char>::LinkedStack<char>, COMDAT

; 100  : {

	mov	QWORD PTR [rsp+8], rcx

; 101  :     topNode = nullptr;

	mov	rax, QWORD PTR this$[rsp]
	mov	QWORD PTR [rax], 0

; 102  :     count = 0;

	mov	rax, QWORD PTR this$[rsp]
	mov	DWORD PTR [rax+8], 0

; 103  : }

	mov	rax, QWORD PTR this$[rsp]
	ret	0
??0?$LinkedStack@D@@QEAA@XZ ENDP			; LinkedStack<char>::LinkedStack<char>
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??_F?$DynamicStack@H@@QEAAXXZ
_TEXT	SEGMENT
this$ = 48
??_F?$DynamicStack@H@@QEAAXXZ PROC			; DynamicStack<int>::`default constructor closure', COMDAT
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
	mov	edx, 10
	mov	rcx, QWORD PTR this$[rsp]
	call	??0?$DynamicStack@H@@QEAA@H@Z		; DynamicStack<int>::DynamicStack<int>
	npad	1
	add	rsp, 40					; 00000028H
	ret	0
??_F?$DynamicStack@H@@QEAAXXZ ENDP			; DynamicStack<int>::`default constructor closure'
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??4?$DynamicStack@H@@QEAAAEAV0@AEBV0@@Z
_TEXT	SEGMENT
this$ = 24
__that$ = 32
??4?$DynamicStack@H@@QEAAAEAV0@AEBV0@@Z PROC		; DynamicStack<int>::operator=, COMDAT
$LN4:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rsi
	push	rdi
	mov	rdi, QWORD PTR this$[rsp]
	mov	rsi, QWORD PTR __that$[rsp]
	mov	ecx, 16
	rep movsb
	mov	rax, QWORD PTR this$[rsp]
	pop	rdi
	pop	rsi
	ret	0
??4?$DynamicStack@H@@QEAAAEAV0@AEBV0@@Z ENDP		; DynamicStack<int>::operator=
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\youss\OneDrive\Documents\ILISI 2\2026 Cpp Avance et Virtualisation\TPs\TP1\StackDLL_Project\Stack.cpp
;	COMDAT ?size@?$DynamicStack@H@@QEBAHXZ
_TEXT	SEGMENT
this$ = 8
?size@?$DynamicStack@H@@QEBAHXZ PROC			; DynamicStack<int>::size, COMDAT

; 89   : {

	mov	QWORD PTR [rsp+8], rcx

; 90   :     return topIndex + 1;

	mov	rax, QWORD PTR this$[rsp]
	mov	eax, DWORD PTR [rax+12]
	inc	eax

; 91   : }

	ret	0
?size@?$DynamicStack@H@@QEBAHXZ ENDP			; DynamicStack<int>::size
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\youss\OneDrive\Documents\ILISI 2\2026 Cpp Avance et Virtualisation\TPs\TP1\StackDLL_Project\Stack.cpp
;	COMDAT ?isEmpty@?$DynamicStack@H@@QEBA_NXZ
_TEXT	SEGMENT
tv66 = 0
this$ = 32
?isEmpty@?$DynamicStack@H@@QEBA_NXZ PROC		; DynamicStack<int>::isEmpty, COMDAT

; 82   : {

$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 24

; 83   :     return topIndex == -1;

	mov	rax, QWORD PTR this$[rsp]
	cmp	DWORD PTR [rax+12], -1
	jne	SHORT $LN3@isEmpty
	mov	DWORD PTR tv66[rsp], 1
	jmp	SHORT $LN4@isEmpty
$LN3@isEmpty:
	mov	DWORD PTR tv66[rsp], 0
$LN4@isEmpty:
	movzx	eax, BYTE PTR tv66[rsp]

; 84   : }

	add	rsp, 24
	ret	0
?isEmpty@?$DynamicStack@H@@QEBA_NXZ ENDP		; DynamicStack<int>::isEmpty
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\youss\OneDrive\Documents\ILISI 2\2026 Cpp Avance et Virtualisation\TPs\TP1\StackDLL_Project\Stack.cpp
;	COMDAT ?top@?$DynamicStack@H@@QEBAHXZ
_TEXT	SEGMENT
$T1 = 32
this$ = 80
?top@?$DynamicStack@H@@QEBAHXZ PROC			; DynamicStack<int>::top, COMDAT

; 70   : {

$LN4:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 72					; 00000048H

; 71   :     if (isEmpty())

	mov	rcx, QWORD PTR this$[rsp]
	call	?isEmpty@?$DynamicStack@H@@QEBA_NXZ	; DynamicStack<int>::isEmpty
	movzx	eax, al
	test	eax, eax
	je	SHORT $LN2@top

; 72   :     {
; 73   :         throw std::runtime_error("Stack is empty");

	lea	rdx, OFFSET FLAT:$SG57802
	lea	rcx, QWORD PTR $T1[rsp]
	call	??0runtime_error@std@@QEAA@PEBD@Z	; std::runtime_error::runtime_error
	lea	rdx, OFFSET FLAT:_TI2?AVruntime_error@std@@
	lea	rcx, QWORD PTR $T1[rsp]
	call	_CxxThrowException
	npad	1
$LN2@top:

; 74   :     }
; 75   : 
; 76   :     return data[topIndex];

	mov	rax, QWORD PTR this$[rsp]
	movsxd	rax, DWORD PTR [rax+12]
	mov	rcx, QWORD PTR this$[rsp]
	mov	rcx, QWORD PTR [rcx]
	mov	eax, DWORD PTR [rcx+rax*4]
$LN3@top:

; 77   : }

	add	rsp, 72					; 00000048H
	ret	0
?top@?$DynamicStack@H@@QEBAHXZ ENDP			; DynamicStack<int>::top
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\youss\OneDrive\Documents\ILISI 2\2026 Cpp Avance et Virtualisation\TPs\TP1\StackDLL_Project\Stack.cpp
;	COMDAT ?pop@?$DynamicStack@H@@QEAAXXZ
_TEXT	SEGMENT
$T1 = 32
this$ = 80
?pop@?$DynamicStack@H@@QEAAXXZ PROC			; DynamicStack<int>::pop, COMDAT

; 58   : {

$LN4:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 72					; 00000048H

; 59   :     if (isEmpty())

	mov	rcx, QWORD PTR this$[rsp]
	call	?isEmpty@?$DynamicStack@H@@QEBA_NXZ	; DynamicStack<int>::isEmpty
	movzx	eax, al
	test	eax, eax
	je	SHORT $LN2@pop

; 60   :     {
; 61   :         throw std::runtime_error("Stack is empty");

	lea	rdx, OFFSET FLAT:$SG57795
	lea	rcx, QWORD PTR $T1[rsp]
	call	??0runtime_error@std@@QEAA@PEBD@Z	; std::runtime_error::runtime_error
	lea	rdx, OFFSET FLAT:_TI2?AVruntime_error@std@@
	lea	rcx, QWORD PTR $T1[rsp]
	call	_CxxThrowException
	npad	1
$LN2@pop:

; 62   :     }
; 63   : 
; 64   :     topIndex--;

	mov	rax, QWORD PTR this$[rsp]
	mov	eax, DWORD PTR [rax+12]
	dec	eax
	mov	rcx, QWORD PTR this$[rsp]
	mov	DWORD PTR [rcx+12], eax
$LN3@pop:

; 65   : }

	add	rsp, 72					; 00000048H
	ret	0
?pop@?$DynamicStack@H@@QEAAXXZ ENDP			; DynamicStack<int>::pop
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\youss\OneDrive\Documents\ILISI 2\2026 Cpp Avance et Virtualisation\TPs\TP1\StackDLL_Project\Stack.cpp
;	COMDAT ?push@?$DynamicStack@H@@QEAAXAEBH@Z
_TEXT	SEGMENT
tv74 = 32
tv83 = 36
tv78 = 40
tv80 = 48
this$ = 80
value$ = 88
?push@?$DynamicStack@H@@QEAAXAEBH@Z PROC		; DynamicStack<int>::push, COMDAT

; 46   : {

$LN4:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 72					; 00000048H

; 47   :     if (topIndex + 1 >= capacity)

	mov	rax, QWORD PTR this$[rsp]
	mov	eax, DWORD PTR [rax+12]
	inc	eax
	mov	rcx, QWORD PTR this$[rsp]
	cmp	eax, DWORD PTR [rcx+8]
	jl	SHORT $LN2@push

; 48   :     {
; 49   :         resize();

	mov	rcx, QWORD PTR this$[rsp]
	call	?resize@?$DynamicStack@H@@AEAAXXZ	; DynamicStack<int>::resize
	npad	1
$LN2@push:

; 50   :     }
; 51   : 
; 52   :     data[++topIndex] = value;

	mov	rax, QWORD PTR value$[rsp]
	mov	eax, DWORD PTR [rax]
	mov	DWORD PTR tv83[rsp], eax
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	QWORD PTR tv80[rsp], rax
	mov	rax, QWORD PTR this$[rsp]
	mov	eax, DWORD PTR [rax+12]
	inc	eax
	mov	DWORD PTR tv74[rsp], eax
	mov	rax, QWORD PTR this$[rsp]
	mov	ecx, DWORD PTR tv74[rsp]
	mov	DWORD PTR [rax+12], ecx
	movsxd	rax, DWORD PTR tv74[rsp]
	shl	rax, 2
	mov	QWORD PTR tv78[rsp], rax
	mov	rax, QWORD PTR tv78[rsp]
	mov	rcx, QWORD PTR tv80[rsp]
	add	rcx, rax
	mov	rax, rcx
	mov	ecx, DWORD PTR tv83[rsp]
	mov	DWORD PTR [rax], ecx

; 53   : }

	add	rsp, 72					; 00000048H
	ret	0
?push@?$DynamicStack@H@@QEAAXAEBH@Z ENDP		; DynamicStack<int>::push
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\youss\OneDrive\Documents\ILISI 2\2026 Cpp Avance et Virtualisation\TPs\TP1\StackDLL_Project\Stack.cpp
;	COMDAT ??1?$DynamicStack@H@@QEAA@XZ
_TEXT	SEGMENT
$T1 = 32
this$ = 64
??1?$DynamicStack@H@@QEAA@XZ PROC			; DynamicStack<int>::~DynamicStack<int>, COMDAT

; 22   : {

$LN4:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H

; 23   :     delete[] data;

	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	QWORD PTR $T1[rsp], rax
	mov	rcx, QWORD PTR $T1[rsp]
	call	??_V@YAXPEAX@Z				; operator delete[]
	npad	1

; 24   : }

	add	rsp, 56					; 00000038H
	ret	0
??1?$DynamicStack@H@@QEAA@XZ ENDP			; DynamicStack<int>::~DynamicStack<int>
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\youss\OneDrive\Documents\ILISI 2\2026 Cpp Avance et Virtualisation\TPs\TP1\StackDLL_Project\Stack.cpp
;	COMDAT ??0?$DynamicStack@H@@QEAA@H@Z
_TEXT	SEGMENT
tv72 = 32
$T1 = 40
this$ = 64
initialCapacity$ = 72
??0?$DynamicStack@H@@QEAA@H@Z PROC			; DynamicStack<int>::DynamicStack<int>, COMDAT

; 9    : {

$LN4:
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H

; 10   :     if (initialCapacity <= 0)

	cmp	DWORD PTR initialCapacity$[rsp], 0
	jg	SHORT $LN2@DynamicSta

; 11   :         initialCapacity = 10;

	mov	DWORD PTR initialCapacity$[rsp], 10
$LN2@DynamicSta:

; 12   : 
; 13   :     capacity = initialCapacity;

	mov	rax, QWORD PTR this$[rsp]
	mov	ecx, DWORD PTR initialCapacity$[rsp]
	mov	DWORD PTR [rax+8], ecx

; 14   :     topIndex = -1;

	mov	rax, QWORD PTR this$[rsp]
	mov	DWORD PTR [rax+12], -1

; 15   : 
; 16   :     data = new T[capacity];

	mov	rax, QWORD PTR this$[rsp]
	movsxd	rax, DWORD PTR [rax+8]
	mov	QWORD PTR tv72[rsp], rax
	mov	eax, 4
	mov	rcx, QWORD PTR tv72[rsp]
	mul	rcx
	mov	rcx, -1
	cmovb	rax, rcx
	mov	rcx, rax
	call	??_U@YAPEAX_K@Z				; operator new[]
	mov	QWORD PTR $T1[rsp], rax
	mov	rax, QWORD PTR this$[rsp]
	mov	rcx, QWORD PTR $T1[rsp]
	mov	QWORD PTR [rax], rcx

; 17   : }

	mov	rax, QWORD PTR this$[rsp]
	add	rsp, 56					; 00000038H
	ret	0
??0?$DynamicStack@H@@QEAA@H@Z ENDP			; DynamicStack<int>::DynamicStack<int>
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\youss\OneDrive\Documents\ILISI 2\2026 Cpp Avance et Virtualisation\TPs\TP1\StackDLL_Project\Stack.cpp
;	COMDAT ?resize@?$DynamicStack@H@@AEAAXXZ
_TEXT	SEGMENT
i$1 = 32
newData$ = 40
tv71 = 48
$T2 = 56
$T3 = 64
this$ = 96
?resize@?$DynamicStack@H@@AEAAXXZ PROC			; DynamicStack<int>::resize, COMDAT

; 29   : {

$LN6:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 88					; 00000058H

; 30   :     capacity *= 2;

	mov	rax, QWORD PTR this$[rsp]
	mov	eax, DWORD PTR [rax+8]
	shl	eax, 1
	mov	rcx, QWORD PTR this$[rsp]
	mov	DWORD PTR [rcx+8], eax

; 31   : 
; 32   :     T* newData = new T[capacity];

	mov	rax, QWORD PTR this$[rsp]
	movsxd	rax, DWORD PTR [rax+8]
	mov	QWORD PTR tv71[rsp], rax
	mov	eax, 4
	mov	rcx, QWORD PTR tv71[rsp]
	mul	rcx
	mov	rcx, -1
	cmovb	rax, rcx
	mov	rcx, rax
	call	??_U@YAPEAX_K@Z				; operator new[]
	mov	QWORD PTR $T2[rsp], rax
	mov	rax, QWORD PTR $T2[rsp]
	mov	QWORD PTR newData$[rsp], rax

; 33   : 
; 34   :     for (int i = 0; i <= topIndex; i++)

	mov	DWORD PTR i$1[rsp], 0
	jmp	SHORT $LN4@resize
$LN2@resize:
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
$LN4@resize:
	mov	rax, QWORD PTR this$[rsp]
	mov	eax, DWORD PTR [rax+12]
	cmp	DWORD PTR i$1[rsp], eax
	jg	SHORT $LN3@resize

; 35   :     {
; 36   :         newData[i] = data[i];

	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	mov	rcx, QWORD PTR [rcx]
	movsxd	rdx, DWORD PTR i$1[rsp]
	mov	r8, QWORD PTR newData$[rsp]
	mov	eax, DWORD PTR [rcx+rax*4]
	mov	DWORD PTR [r8+rdx*4], eax

; 37   :     }

	jmp	SHORT $LN2@resize
$LN3@resize:

; 38   : 
; 39   :     delete[] data;

	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	QWORD PTR $T3[rsp], rax
	mov	rcx, QWORD PTR $T3[rsp]
	call	??_V@YAXPEAX@Z				; operator delete[]
	npad	1

; 40   :     data = newData;

	mov	rax, QWORD PTR this$[rsp]
	mov	rcx, QWORD PTR newData$[rsp]
	mov	QWORD PTR [rax], rcx

; 41   : }

	add	rsp, 88					; 00000058H
	ret	0
?resize@?$DynamicStack@H@@AEAAXXZ ENDP			; DynamicStack<int>::resize
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??_F?$DynamicStack@D@@QEAAXXZ
_TEXT	SEGMENT
this$ = 48
??_F?$DynamicStack@D@@QEAAXXZ PROC			; DynamicStack<char>::`default constructor closure', COMDAT
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
	mov	edx, 10
	mov	rcx, QWORD PTR this$[rsp]
	call	??0?$DynamicStack@D@@QEAA@H@Z		; DynamicStack<char>::DynamicStack<char>
	npad	1
	add	rsp, 40					; 00000028H
	ret	0
??_F?$DynamicStack@D@@QEAAXXZ ENDP			; DynamicStack<char>::`default constructor closure'
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??4?$DynamicStack@D@@QEAAAEAV0@AEBV0@@Z
_TEXT	SEGMENT
this$ = 24
__that$ = 32
??4?$DynamicStack@D@@QEAAAEAV0@AEBV0@@Z PROC		; DynamicStack<char>::operator=, COMDAT
$LN4:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rsi
	push	rdi
	mov	rdi, QWORD PTR this$[rsp]
	mov	rsi, QWORD PTR __that$[rsp]
	mov	ecx, 16
	rep movsb
	mov	rax, QWORD PTR this$[rsp]
	pop	rdi
	pop	rsi
	ret	0
??4?$DynamicStack@D@@QEAAAEAV0@AEBV0@@Z ENDP		; DynamicStack<char>::operator=
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\youss\OneDrive\Documents\ILISI 2\2026 Cpp Avance et Virtualisation\TPs\TP1\StackDLL_Project\Stack.cpp
;	COMDAT ?size@?$DynamicStack@D@@QEBAHXZ
_TEXT	SEGMENT
this$ = 8
?size@?$DynamicStack@D@@QEBAHXZ PROC			; DynamicStack<char>::size, COMDAT

; 89   : {

	mov	QWORD PTR [rsp+8], rcx

; 90   :     return topIndex + 1;

	mov	rax, QWORD PTR this$[rsp]
	mov	eax, DWORD PTR [rax+12]
	inc	eax

; 91   : }

	ret	0
?size@?$DynamicStack@D@@QEBAHXZ ENDP			; DynamicStack<char>::size
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\youss\OneDrive\Documents\ILISI 2\2026 Cpp Avance et Virtualisation\TPs\TP1\StackDLL_Project\Stack.cpp
;	COMDAT ?isEmpty@?$DynamicStack@D@@QEBA_NXZ
_TEXT	SEGMENT
tv66 = 0
this$ = 32
?isEmpty@?$DynamicStack@D@@QEBA_NXZ PROC		; DynamicStack<char>::isEmpty, COMDAT

; 82   : {

$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 24

; 83   :     return topIndex == -1;

	mov	rax, QWORD PTR this$[rsp]
	cmp	DWORD PTR [rax+12], -1
	jne	SHORT $LN3@isEmpty
	mov	DWORD PTR tv66[rsp], 1
	jmp	SHORT $LN4@isEmpty
$LN3@isEmpty:
	mov	DWORD PTR tv66[rsp], 0
$LN4@isEmpty:
	movzx	eax, BYTE PTR tv66[rsp]

; 84   : }

	add	rsp, 24
	ret	0
?isEmpty@?$DynamicStack@D@@QEBA_NXZ ENDP		; DynamicStack<char>::isEmpty
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\youss\OneDrive\Documents\ILISI 2\2026 Cpp Avance et Virtualisation\TPs\TP1\StackDLL_Project\Stack.cpp
;	COMDAT ?top@?$DynamicStack@D@@QEBADXZ
_TEXT	SEGMENT
$T1 = 32
this$ = 80
?top@?$DynamicStack@D@@QEBADXZ PROC			; DynamicStack<char>::top, COMDAT

; 70   : {

$LN4:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 72					; 00000048H

; 71   :     if (isEmpty())

	mov	rcx, QWORD PTR this$[rsp]
	call	?isEmpty@?$DynamicStack@D@@QEBA_NXZ	; DynamicStack<char>::isEmpty
	movzx	eax, al
	test	eax, eax
	je	SHORT $LN2@top

; 72   :     {
; 73   :         throw std::runtime_error("Stack is empty");

	lea	rdx, OFFSET FLAT:$SG57749
	lea	rcx, QWORD PTR $T1[rsp]
	call	??0runtime_error@std@@QEAA@PEBD@Z	; std::runtime_error::runtime_error
	lea	rdx, OFFSET FLAT:_TI2?AVruntime_error@std@@
	lea	rcx, QWORD PTR $T1[rsp]
	call	_CxxThrowException
	npad	1
$LN2@top:

; 74   :     }
; 75   : 
; 76   :     return data[topIndex];

	mov	rax, QWORD PTR this$[rsp]
	movsxd	rax, DWORD PTR [rax+12]
	mov	rcx, QWORD PTR this$[rsp]
	mov	rcx, QWORD PTR [rcx]
	movzx	eax, BYTE PTR [rcx+rax]
$LN3@top:

; 77   : }

	add	rsp, 72					; 00000048H
	ret	0
?top@?$DynamicStack@D@@QEBADXZ ENDP			; DynamicStack<char>::top
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\youss\OneDrive\Documents\ILISI 2\2026 Cpp Avance et Virtualisation\TPs\TP1\StackDLL_Project\Stack.cpp
;	COMDAT ?pop@?$DynamicStack@D@@QEAAXXZ
_TEXT	SEGMENT
$T1 = 32
this$ = 80
?pop@?$DynamicStack@D@@QEAAXXZ PROC			; DynamicStack<char>::pop, COMDAT

; 58   : {

$LN4:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 72					; 00000048H

; 59   :     if (isEmpty())

	mov	rcx, QWORD PTR this$[rsp]
	call	?isEmpty@?$DynamicStack@D@@QEBA_NXZ	; DynamicStack<char>::isEmpty
	movzx	eax, al
	test	eax, eax
	je	SHORT $LN2@pop

; 60   :     {
; 61   :         throw std::runtime_error("Stack is empty");

	lea	rdx, OFFSET FLAT:$SG57742
	lea	rcx, QWORD PTR $T1[rsp]
	call	??0runtime_error@std@@QEAA@PEBD@Z	; std::runtime_error::runtime_error
	lea	rdx, OFFSET FLAT:_TI2?AVruntime_error@std@@
	lea	rcx, QWORD PTR $T1[rsp]
	call	_CxxThrowException
	npad	1
$LN2@pop:

; 62   :     }
; 63   : 
; 64   :     topIndex--;

	mov	rax, QWORD PTR this$[rsp]
	mov	eax, DWORD PTR [rax+12]
	dec	eax
	mov	rcx, QWORD PTR this$[rsp]
	mov	DWORD PTR [rcx+12], eax
$LN3@pop:

; 65   : }

	add	rsp, 72					; 00000048H
	ret	0
?pop@?$DynamicStack@D@@QEAAXXZ ENDP			; DynamicStack<char>::pop
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\youss\OneDrive\Documents\ILISI 2\2026 Cpp Avance et Virtualisation\TPs\TP1\StackDLL_Project\Stack.cpp
;	COMDAT ?push@?$DynamicStack@D@@QEAAXAEBD@Z
_TEXT	SEGMENT
tv83 = 32
tv74 = 36
tv78 = 40
tv80 = 48
this$ = 80
value$ = 88
?push@?$DynamicStack@D@@QEAAXAEBD@Z PROC		; DynamicStack<char>::push, COMDAT

; 46   : {

$LN4:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 72					; 00000048H

; 47   :     if (topIndex + 1 >= capacity)

	mov	rax, QWORD PTR this$[rsp]
	mov	eax, DWORD PTR [rax+12]
	inc	eax
	mov	rcx, QWORD PTR this$[rsp]
	cmp	eax, DWORD PTR [rcx+8]
	jl	SHORT $LN2@push

; 48   :     {
; 49   :         resize();

	mov	rcx, QWORD PTR this$[rsp]
	call	?resize@?$DynamicStack@D@@AEAAXXZ	; DynamicStack<char>::resize
	npad	1
$LN2@push:

; 50   :     }
; 51   : 
; 52   :     data[++topIndex] = value;

	mov	rax, QWORD PTR value$[rsp]
	movzx	eax, BYTE PTR [rax]
	mov	BYTE PTR tv83[rsp], al
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	QWORD PTR tv80[rsp], rax
	mov	rax, QWORD PTR this$[rsp]
	mov	eax, DWORD PTR [rax+12]
	inc	eax
	mov	DWORD PTR tv74[rsp], eax
	mov	rax, QWORD PTR this$[rsp]
	mov	ecx, DWORD PTR tv74[rsp]
	mov	DWORD PTR [rax+12], ecx
	movsxd	rax, DWORD PTR tv74[rsp]
	mov	QWORD PTR tv78[rsp], rax
	mov	rax, QWORD PTR tv78[rsp]
	mov	rcx, QWORD PTR tv80[rsp]
	add	rcx, rax
	mov	rax, rcx
	movzx	ecx, BYTE PTR tv83[rsp]
	mov	BYTE PTR [rax], cl

; 53   : }

	add	rsp, 72					; 00000048H
	ret	0
?push@?$DynamicStack@D@@QEAAXAEBD@Z ENDP		; DynamicStack<char>::push
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\youss\OneDrive\Documents\ILISI 2\2026 Cpp Avance et Virtualisation\TPs\TP1\StackDLL_Project\Stack.cpp
;	COMDAT ??1?$DynamicStack@D@@QEAA@XZ
_TEXT	SEGMENT
$T1 = 32
this$ = 64
??1?$DynamicStack@D@@QEAA@XZ PROC			; DynamicStack<char>::~DynamicStack<char>, COMDAT

; 22   : {

$LN4:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H

; 23   :     delete[] data;

	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	QWORD PTR $T1[rsp], rax
	mov	rcx, QWORD PTR $T1[rsp]
	call	??_V@YAXPEAX@Z				; operator delete[]
	npad	1

; 24   : }

	add	rsp, 56					; 00000038H
	ret	0
??1?$DynamicStack@D@@QEAA@XZ ENDP			; DynamicStack<char>::~DynamicStack<char>
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\youss\OneDrive\Documents\ILISI 2\2026 Cpp Avance et Virtualisation\TPs\TP1\StackDLL_Project\Stack.cpp
;	COMDAT ??0?$DynamicStack@D@@QEAA@H@Z
_TEXT	SEGMENT
$T1 = 32
this$ = 64
initialCapacity$ = 72
??0?$DynamicStack@D@@QEAA@H@Z PROC			; DynamicStack<char>::DynamicStack<char>, COMDAT

; 9    : {

$LN4:
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 56					; 00000038H

; 10   :     if (initialCapacity <= 0)

	cmp	DWORD PTR initialCapacity$[rsp], 0
	jg	SHORT $LN2@DynamicSta

; 11   :         initialCapacity = 10;

	mov	DWORD PTR initialCapacity$[rsp], 10
$LN2@DynamicSta:

; 12   : 
; 13   :     capacity = initialCapacity;

	mov	rax, QWORD PTR this$[rsp]
	mov	ecx, DWORD PTR initialCapacity$[rsp]
	mov	DWORD PTR [rax+8], ecx

; 14   :     topIndex = -1;

	mov	rax, QWORD PTR this$[rsp]
	mov	DWORD PTR [rax+12], -1

; 15   : 
; 16   :     data = new T[capacity];

	mov	rax, QWORD PTR this$[rsp]
	movsxd	rax, DWORD PTR [rax+8]
	mov	rcx, rax
	call	??_U@YAPEAX_K@Z				; operator new[]
	mov	QWORD PTR $T1[rsp], rax
	mov	rax, QWORD PTR this$[rsp]
	mov	rcx, QWORD PTR $T1[rsp]
	mov	QWORD PTR [rax], rcx

; 17   : }

	mov	rax, QWORD PTR this$[rsp]
	add	rsp, 56					; 00000038H
	ret	0
??0?$DynamicStack@D@@QEAA@H@Z ENDP			; DynamicStack<char>::DynamicStack<char>
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Users\youss\OneDrive\Documents\ILISI 2\2026 Cpp Avance et Virtualisation\TPs\TP1\StackDLL_Project\Stack.cpp
;	COMDAT ?resize@?$DynamicStack@D@@AEAAXXZ
_TEXT	SEGMENT
i$1 = 32
newData$ = 40
$T2 = 48
$T3 = 56
this$ = 80
?resize@?$DynamicStack@D@@AEAAXXZ PROC			; DynamicStack<char>::resize, COMDAT

; 29   : {

$LN6:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 72					; 00000048H

; 30   :     capacity *= 2;

	mov	rax, QWORD PTR this$[rsp]
	mov	eax, DWORD PTR [rax+8]
	shl	eax, 1
	mov	rcx, QWORD PTR this$[rsp]
	mov	DWORD PTR [rcx+8], eax

; 31   : 
; 32   :     T* newData = new T[capacity];

	mov	rax, QWORD PTR this$[rsp]
	movsxd	rax, DWORD PTR [rax+8]
	mov	rcx, rax
	call	??_U@YAPEAX_K@Z				; operator new[]
	mov	QWORD PTR $T2[rsp], rax
	mov	rax, QWORD PTR $T2[rsp]
	mov	QWORD PTR newData$[rsp], rax

; 33   : 
; 34   :     for (int i = 0; i <= topIndex; i++)

	mov	DWORD PTR i$1[rsp], 0
	jmp	SHORT $LN4@resize
$LN2@resize:
	mov	eax, DWORD PTR i$1[rsp]
	inc	eax
	mov	DWORD PTR i$1[rsp], eax
$LN4@resize:
	mov	rax, QWORD PTR this$[rsp]
	mov	eax, DWORD PTR [rax+12]
	cmp	DWORD PTR i$1[rsp], eax
	jg	SHORT $LN3@resize

; 35   :     {
; 36   :         newData[i] = data[i];

	movsxd	rax, DWORD PTR i$1[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	mov	rcx, QWORD PTR [rcx]
	movsxd	rdx, DWORD PTR i$1[rsp]
	mov	r8, QWORD PTR newData$[rsp]
	movzx	eax, BYTE PTR [rcx+rax]
	mov	BYTE PTR [r8+rdx], al

; 37   :     }

	jmp	SHORT $LN2@resize
$LN3@resize:

; 38   : 
; 39   :     delete[] data;

	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax]
	mov	QWORD PTR $T3[rsp], rax
	mov	rcx, QWORD PTR $T3[rsp]
	call	??_V@YAXPEAX@Z				; operator delete[]
	npad	1

; 40   :     data = newData;

	mov	rax, QWORD PTR this$[rsp]
	mov	rcx, QWORD PTR newData$[rsp]
	mov	QWORD PTR [rax], rcx

; 41   : }

	add	rsp, 72					; 00000048H
	ret	0
?resize@?$DynamicStack@D@@AEAAXXZ ENDP			; DynamicStack<char>::resize
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??_Gruntime_error@std@@UEAAPEAXI@Z
_TEXT	SEGMENT
this$ = 48
__flags$ = 56
??_Gruntime_error@std@@UEAAPEAXI@Z PROC			; std::runtime_error::`scalar deleting destructor', COMDAT
$LN5:
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
	mov	rcx, QWORD PTR this$[rsp]
	call	??1runtime_error@std@@UEAA@XZ
	mov	eax, DWORD PTR __flags$[rsp]
	and	eax, 1
	test	eax, eax
	je	SHORT $LN2@scalar
	mov	edx, 24
	mov	rcx, QWORD PTR this$[rsp]
	call	??3@YAXPEAX_K@Z				; operator delete
	npad	1
$LN2@scalar:
	mov	rax, QWORD PTR this$[rsp]
	add	rsp, 40					; 00000028H
	ret	0
??_Gruntime_error@std@@UEAAPEAXI@Z ENDP			; std::runtime_error::`scalar deleting destructor'
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??0runtime_error@std@@QEAA@AEBV01@@Z
_TEXT	SEGMENT
this$ = 48
__that$ = 56
??0runtime_error@std@@QEAA@AEBV01@@Z PROC		; std::runtime_error::runtime_error, COMDAT
$LN4:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
	mov	rdx, QWORD PTR __that$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	??0exception@std@@QEAA@AEBV01@@Z	; std::exception::exception
	mov	rax, QWORD PTR this$[rsp]
	lea	rcx, OFFSET FLAT:??_7runtime_error@std@@6B@
	mov	QWORD PTR [rax], rcx
	mov	rax, QWORD PTR this$[rsp]
	add	rsp, 40					; 00000028H
	ret	0
??0runtime_error@std@@QEAA@AEBV01@@Z ENDP		; std::runtime_error::runtime_error
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??1runtime_error@std@@UEAA@XZ
_TEXT	SEGMENT
this$ = 48
??1runtime_error@std@@UEAA@XZ PROC			; std::runtime_error::~runtime_error, COMDAT
$LN4:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
	mov	rcx, QWORD PTR this$[rsp]
	call	??1exception@std@@UEAA@XZ		; std::exception::~exception
	npad	1
	add	rsp, 40					; 00000028H
	ret	0
??1runtime_error@std@@UEAA@XZ ENDP			; std::runtime_error::~runtime_error
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.44.35207\include\stdexcept
;	COMDAT ??0runtime_error@std@@QEAA@PEBD@Z
_TEXT	SEGMENT
this$ = 48
_Message$ = 56
??0runtime_error@std@@QEAA@PEBD@Z PROC			; std::runtime_error::runtime_error, COMDAT

; 106  :     explicit runtime_error(const char* _Message) : _Mybase(_Message) {}

$LN4:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
	mov	rdx, QWORD PTR _Message$[rsp]
	mov	rcx, QWORD PTR this$[rsp]
	call	??0exception@std@@QEAA@QEBD@Z		; std::exception::exception
	mov	rax, QWORD PTR this$[rsp]
	lea	rcx, OFFSET FLAT:??_7runtime_error@std@@6B@
	mov	QWORD PTR [rax], rcx
	mov	rax, QWORD PTR this$[rsp]
	add	rsp, 40					; 00000028H
	ret	0
??0runtime_error@std@@QEAA@PEBD@Z ENDP			; std::runtime_error::runtime_error
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ??_Gexception@std@@UEAAPEAXI@Z
_TEXT	SEGMENT
this$ = 48
__flags$ = 56
??_Gexception@std@@UEAAPEAXI@Z PROC			; std::exception::`scalar deleting destructor', COMDAT
$LN5:
	mov	DWORD PTR [rsp+16], edx
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
	mov	rcx, QWORD PTR this$[rsp]
	call	??1exception@std@@UEAA@XZ		; std::exception::~exception
	mov	eax, DWORD PTR __flags$[rsp]
	and	eax, 1
	test	eax, eax
	je	SHORT $LN2@scalar
	mov	edx, 24
	mov	rcx, QWORD PTR this$[rsp]
	call	??3@YAXPEAX_K@Z				; operator delete
	npad	1
$LN2@scalar:
	mov	rax, QWORD PTR this$[rsp]
	add	rsp, 40					; 00000028H
	ret	0
??_Gexception@std@@UEAAPEAXI@Z ENDP			; std::exception::`scalar deleting destructor'
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.44.35207\include\vcruntime_exception.h
;	COMDAT ?what@exception@std@@UEBAPEBDXZ
_TEXT	SEGMENT
tv69 = 0
this$ = 32
?what@exception@std@@UEBAPEBDXZ PROC			; std::exception::what, COMDAT

; 95   :     {

$LN5:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 24

; 96   :         return _Data._What ? _Data._What : "Unknown exception";

	mov	rax, QWORD PTR this$[rsp]
	cmp	QWORD PTR [rax+8], 0
	je	SHORT $LN3@what
	mov	rax, QWORD PTR this$[rsp]
	mov	rax, QWORD PTR [rax+8]
	mov	QWORD PTR tv69[rsp], rax
	jmp	SHORT $LN4@what
$LN3@what:
	lea	rax, OFFSET FLAT:??_C@_0BC@EOODALEL@Unknown?5exception@
	mov	QWORD PTR tv69[rsp], rax
$LN4@what:
	mov	rax, QWORD PTR tv69[rsp]

; 97   :     }

	add	rsp, 24
	ret	0
?what@exception@std@@UEBAPEBDXZ ENDP			; std::exception::what
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.44.35207\include\vcruntime_exception.h
;	COMDAT ??1exception@std@@UEAA@XZ
_TEXT	SEGMENT
this$ = 48
??1exception@std@@UEAA@XZ PROC				; std::exception::~exception, COMDAT

; 90   :     {

$LN4:
	mov	QWORD PTR [rsp+8], rcx
	sub	rsp, 40					; 00000028H
	mov	rax, QWORD PTR this$[rsp]
	lea	rcx, OFFSET FLAT:??_7exception@std@@6B@
	mov	QWORD PTR [rax], rcx

; 91   :         __std_exception_destroy(&_Data);

	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, rax
	call	__std_exception_destroy
	npad	1

; 92   :     }

	add	rsp, 40					; 00000028H
	ret	0
??1exception@std@@UEAA@XZ ENDP				; std::exception::~exception
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.44.35207\include\vcruntime_exception.h
;	COMDAT ??0exception@std@@QEAA@AEBV01@@Z
_TEXT	SEGMENT
this$ = 48
_Other$ = 56
??0exception@std@@QEAA@AEBV01@@Z PROC			; std::exception::exception, COMDAT

; 73   :     {

$LN4:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rdi
	sub	rsp, 32					; 00000020H
	mov	rax, QWORD PTR this$[rsp]
	lea	rcx, OFFSET FLAT:??_7exception@std@@6B@
	mov	QWORD PTR [rax], rcx

; 72   :         : _Data()

	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 16
	rep stosb

; 74   :         __std_exception_copy(&_Other._Data, &_Data);

	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rcx, QWORD PTR _Other$[rsp]
	add	rcx, 8
	mov	rdx, rax
	call	__std_exception_copy
	npad	1

; 75   :     }

	mov	rax, QWORD PTR this$[rsp]
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
??0exception@std@@QEAA@AEBV01@@Z ENDP			; std::exception::exception
_TEXT	ENDS
; Function compile flags: /Odtp
; File C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.44.35207\include\vcruntime_exception.h
;	COMDAT ??0exception@std@@QEAA@QEBD@Z
_TEXT	SEGMENT
_InitData$ = 32
this$ = 64
_Message$ = 72
??0exception@std@@QEAA@QEBD@Z PROC			; std::exception::exception, COMDAT

; 60   :     {

$LN4:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rdi
	sub	rsp, 48					; 00000030H
	mov	rax, QWORD PTR this$[rsp]
	lea	rcx, OFFSET FLAT:??_7exception@std@@6B@
	mov	QWORD PTR [rax], rcx

; 59   :         : _Data()

	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rdi, rax
	xor	eax, eax
	mov	ecx, 16
	rep stosb

; 61   :         __std_exception_data _InitData = { _Message, true };

	mov	rax, QWORD PTR _Message$[rsp]
	mov	QWORD PTR _InitData$[rsp], rax
	mov	BYTE PTR _InitData$[rsp+8], 1

; 62   :         __std_exception_copy(&_InitData, &_Data);

	mov	rax, QWORD PTR this$[rsp]
	add	rax, 8
	mov	rdx, rax
	lea	rcx, QWORD PTR _InitData$[rsp]
	call	__std_exception_copy
	npad	1

; 63   :     }

	mov	rax, QWORD PTR this$[rsp]
	add	rsp, 48					; 00000030H
	pop	rdi
	ret	0
??0exception@std@@QEAA@QEBD@Z ENDP			; std::exception::exception
_TEXT	ENDS
END
